### ISSUE TITLE
Why the 500 item truncation?

### ISSUE THREAD

**Issue by no-identd** [x28de/mytool#3]
I can see that there's code here:
https://github.com/x28de/mytool/blob/ee39866a0a7667456dbf1d39d79e554fcce6996f/src/de/x28hd/tool/SplitIntoNew.java#L34

And here:
https://github.com/x28de/mytool/blob/ee39866a0a7667456dbf1d39d79e554fcce6996f/src/de/x28hd/tool/SplitIntoNew.java#L85

Which truncates imports at a seemingly arbitrary point. Please, could you perhaps elaborate on the design decision behind this?

**Comment by x28de** [comment]
Hi no-identd, thanks for your interest. 
The truncation is an initial approach for raw input where the placement of items is just in columns of 10, which would need to be panned to the right. More than 300 or 400 such items would be certainly too cumbersome for me, so I thought 500 might be a reasonable limit. (Note that you can add more items with another  drag'n'drop input as often as you want.) I use this method typically for close reading of an unstructured text, split into paragraphs or even single sentences. If learn more about other use cases -- and what use cases might still be useful with such long lists -- I might tidy up this code to lift the limit.
